### ISSUE TITLE
json inputs config payload packet size limit insufficient to fully configure a Rack32 monitoring all 128 inputs of a 32port LSC

### ISSUE THREAD

**Issue by dweston** [SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW#15]
There appears to be a size limit to the json input configuration payload that means it is currently not possible to fully set up a Rack32 connected to a 32port LSC employing a single mqtt packet. As a consequence, if the Rack32 is configured using multiple config packets to cover the full 128 inputs set, the device becomes vulnerable to losing part of its configuration post a power recycle or reset event. Obviously only the last retained partial config packet will be properly re-instated following reinitialisation.

This outcome is repeatable in that if a Rack32 is flashed with latest default firmware v3.3.2, set-up via its Webserver GUI to connect with a local broker and is then configured via a mqtt published `retained` message packet comprised as follows:
*topic*
```conf/xxxxxx```
*json payload*
covering indexes 1 to 128 in the form as per the text file at this link [https://pastebin.com/6SQ4PDvR](url)
the config will fail. Note PasteBin is reporting the file size of this json payload example is 5.04 KB.

It will also fail if the payload covers indexes 1 - 96 input configurations. But if the payload is reduced to only covering indexes 1 - 64 the config upload will work, and consistently so. The file size for this workable version is 2.51 KB [https://pastebin.com/d0nxQdVX](url).

Hence in order to fully configure a Rack32 monitoring a 32port LSC board, a second packet covering indexes 95 - 128 is required. A json payload covering the remaining inputs 65 - 128 is of a similar size [https://pastebin.com/JX3RbEcV](url).

It therefore looks likely that the config routine can only handle up to 64 input elements in one message payload.

Is there scope for raising the size limit for ingestion of an input config packet to an amount exceeding that required for full confiuration of a Rack32 monitoring all 128 inputs of a 32port LSC in one mqtt message packet?

**Comment by moinmoin-sh** [comment]
The QXRS-MQTT-lib throws an error : 
`[ra32] failed to deserialise mqtt json payload`

This is caused by a too small DynamicJsonDocument : 
_[OXRS_MQTT.cpp line 183]_ `DynamicJsonDocument json(MQTT_MAX_MESSAGE_SIZE);`  
MQTT_MAX_MESSAGE_SIZE is declared as `#define MQTT_MAX_MESSAGE_SIZE   4096`

The `ArduinoJson Asistant`  calculates a recommended size of 6144

We need a better way to calculate/forecast the required size of the DynamicJsonDocument that holds the deserialized MQTT-payload. I'm sure @sumnerboy12 will take care for this when he is back.

For experienced user:
If you are compiling the FW by your own, you can use this quick and dirty workaround : 
just change the line 183 in `OXRS_MQTT.cpp` to this (doubles the size) 
_[OXRS_MQTT.cpp line 183]_ `DynamicJsonDocument json(MQTT_MAX_MESSAGE_SIZE * 2);`  
and recompile OXRS-SHA-StateMonitor-ESP32-FW.ino

**Comment by sumnerboy12** [comment]
I think we just increase `MQTT_MAX_MESSAGE_SIZE` to 8192. There is plenty of room on the ESP32. But we might want to determine how big the biggest payload could be - i.e. full `type` and `invert` config for all 128 inputs - to make sure we are covered for anything.

**Comment by sumnerboy12** [comment]
[OXRS-SHA-StateMonitor-ESP32-FW.ino.esp32-TEST.zip](https://github.com/SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW/files/7799838/OXRS-SHA-StateMonitor-ESP32-FW.ino.esp32-TEST.zip)

@dweston here is a test build for the State Monitor firmware with the `MQTT_MAX_MESSAGE_SIZE` increased to 16kB. Would you be able to test this and see how it goes? If you report a successful test I will merge this change and cut a new official release of the firmware.

**Comment by dweston** [comment]
Thx - Ben,

Unfortunately I’m currently on holiday with my family for the next 10 days or so. I will test this version immediately on my return next week.

Ciao

Dion

Sent from my iPhone
+61 408 859 267
